require("custom.disable")
require("custom.functions")
require("custom.statuscolumn")
require("custom.options")
require("custom.autocommands")
require("custom.plugins")
require("custom.keymaps")
require("custom.toggle_stuff")
